### ISSUE TITLE
Maintaining this Repo

### ISSUE THREAD

**Issue by jfullstackdev** [Glank/Java-Games#13]
I have been thinking how this one will be maintained efficiently. Personally, I want to unit test every game, but this is really hard because all the games are in the same repo. And so many refactors, I want to do also. 

I have one suggestion, we keep this repo, but we just provide links to the games. Each game will be a separate repo. It's really hard to maintain when a repo contains several projects particularly when we want to release the games, each should be released separately. 

Hoping there is a response. Thanks.

**Comment by Glank** [comment]
Feel free to grab any of these games and put them in your own repo, just cite back please and include the same license. These were projects from back when I was in college, so I really don't keep them maintained.
